# Generated by Django 6.0.5 on 2026-05-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoIA',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=50)),
                ('probabilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ForeignKey(db_column='id_imagen', on_delete=django.db.models.deletion.CASCADE, to='imagenes.imagendental')),
            ],
            options={
                'db_table': 'diagnostico_ia',
            },
        ),
    ]
