# Generated by Django 6.0.5 on 2026-05-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDental',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes_dentales/')),
                ('ruta_imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_imagen', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_consulta', models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.consulta')),
            ],
            options={
                'db_table': 'imagen_dental',
            },
        ),
    ]
